In [1]:
import pandas as pd
df_aucs = pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/aucs.csv")
df_aucs["far_neg_higher?"] = df_aucs["far_neg_only_aucs"] > df_aucs["close_neg_only_aucs"]
df_aucs

,Unnamed: 0,keyword,all_aps,all_aucs,far_neg_only_aps,far_neg_only_aucs,close_neg_only_aps,close_neg_only_aucs,far_neg_higher?
0,0,àpɾí,0.077434,0.430000,0.081550,0.408,0.622284,0.65,False
1,1,ðɔ̀mɔ̀cɔ̀,0.104252,0.600000,0.113136,0.600,0.554806,0.60,False
2,2,lɛ́ŋgɛ́n,0.211862,0.617273,0.219175,0.626,0.694770,0.53,True
3,3,ŋɔ̀ɽíŋgɔ́,0.102024,0.515455,0.113367,0.517,0.518862,0.50,True
4,4,mùðù,0.177879,0.605455,0.182660,0.593,0.763205,0.73,False
5,5,ùɾnɔ̀,0.074333,0.416364,0.081097,0.416,0.466843,0.42,False
6,6,ðàŋàl,0.118646,0.623636,0.127830,0.620,0.619720,0.66,False
7,7,kə̀və̀lɛ̀ðɔ́,0.150177,0.524545,0.161800,0.528,0.573603,0.49,True
8,8,kàŋú,0.133653,0.480000,0.138016,0.472,0.669836,0.56,False
9,9,íŋgá_nɔ̀nà,0.130706,0.660000,0.152536,0.680,0.481864,0.46,True

In [2]:
pd.set_option("display.float_format", "{:.4f}".format)
df_aucs.columns = df_aucs.columns.str.strip()
df_aucs.sort_values(by=["all_aps"], ascending = False)

,Unnamed: 0,keyword,all_aps,all_aucs,far_neg_only_aps,far_neg_only_aucs,close_neg_only_aps,close_neg_only_aucs,far_neg_higher?
2,2,lɛ́ŋgɛ́n,0.2119,0.6173,0.2192,0.6260,0.6948,0.5300,True
4,4,mùðù,0.1779,0.6055,0.1827,0.5930,0.7632,0.7300,False
7,7,kə̀və̀lɛ̀ðɔ́,0.1502,0.5245,0.1618,0.5280,0.5736,0.4900,True
8,8,kàŋú,0.1337,0.4800,0.1380,0.4720,0.6698,0.5600,False
9,9,íŋgá_nɔ̀nà,0.1307,0.6600,0.1525,0.6800,0.4819,0.4600,True
6,6,ðàŋàl,0.1186,0.6236,0.1278,0.6200,0.6197,0.6600,False
1,1,ðɔ̀mɔ̀cɔ̀,0.1043,0.6000,0.1131,0.6000,0.5548,0.6000,False
3,3,ŋɔ̀ɽíŋgɔ́,0.1020,0.5155,0.1134,0.5170,0.5189,0.5000,True
0,0,àpɾí,0.0774,0.4300,0.0816,0.4080,0.6223,0.6500,False
5,5,ùɾnɔ̀,0.0743,0.4164,0.0811,0.4160,0.4668,0.4200,False

In [4]:
import pandas as pd
from IPython.display import display
df_muthu= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/mùðù.csv")

# sorting by record type and wctc loss
df_muthu = df_muthu.sort_values(by=["record_type","wctc_loss"], ascending = [True, False])

df_muthu.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [6]:

# sorting by wctc loss
df_muthu = df_muthu.sort_values(by=["wctc_loss"], ascending = False)

df_muthu.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [7]:
df_urno= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/ùɾnɔ̀.csv")

# sorting by record type and wctc loss
df_urno = df_urno.sort_values(by=["wctc_loss"], ascending = [False])

df_urno.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [8]:
df_apri= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/àpɾí.csv")

# sorting by record type and wctc loss
df_apri = df_apri.sort_values(by=["wctc_loss"], ascending = [False])

df_apri.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [9]:
df_thomocho= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/ðɔ̀mɔ̀cɔ̀.csv")

# sorting by record type and wctc loss
df_thomocho = df_thomocho.sort_values(by=["wctc_loss"], ascending = [False])

df_thomocho.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [10]:
df_kavletho= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/kə̀və̀lɛ̀ðɔ́.csv")

# sorting by record type and wctc loss
df_kavletho = df_kavletho.sort_values(by=["wctc_loss"], ascending = [False])

df_kavletho.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [11]:
df_kanu= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/kàŋú.csv")

# sorting by record type and wctc loss
df_kanu = df_kanu.sort_values(by=["wctc_loss"], ascending = [False])

df_kanu.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [12]:
df_thanal= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/ðàŋàl.csv")

# sorting by record type and wctc loss
df_thanal = df_thanal.sort_values(by=["wctc_loss"], ascending = [False])

df_thanal.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [13]:
df_lengen= pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/lɛ́ŋgɛ́n.csv")

# sorting by record type and wctc loss
df_lengen = df_lengen.sort_values(by=["wctc_loss"], ascending = [False])

df_lengen.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [14]:
df_inga_nona = pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/íŋgá_nɔ̀nà.csv")

# sorting by record type and wctc loss
df_inga_nona = df_inga_nona.sort_values(by=["wctc_loss"], ascending = [False])

df_inga_nona.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )

In [16]:
df_noringo = pd.read_csv("/home/ekuznetsova/tira_kws/notebooks/analysis_dfs/ŋɔ̀ɽíŋgɔ́.csv")

# sorting by record type and wctc loss
df_noringo = df_noringo.sort_values(by=["wctc_loss"], ascending = [False])

df_noringo.style.set_properties(subset=["sentence"],
                        **{"min-width":"200px",
                           "max-width":"400px"}
                        )